################################################################
# API and dashboard configuration
################################################################
[api]
  insecure = true

################################################################
# Docker configuration backend
################################################################
[providers.docker]
  exposedByDefault = false

################################################################
# EntryPoints configuration
################################################################
[entryPoints]
  [entryPoints.http]
    address = ":80"

################################################################
# Traefik logs configuration
################################################################
[log]
  level = "DEBUG"
  filePath = "logs/traefik.log"

################################################################
# Access logs configuration
################################################################
[accessLog]
  filePath = "logs/access.log"
